[tool.poetry]
name = "nixfetch"
version = "0.1.0"
description = ""
authors = ["Author Name <author@example.com>"]
readme = "README.md"
license = "MIT"
packages = [
  { include = "rich" }
]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "nixfetch"
dynamic = ["version"]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
dependencies = [
    "rich"
    ]
keywords = ["nix", "flake", "stats"]
authors = [
  {name = "Povl Filip Sonne-Frederiksen"}
]

[project.scripts]
nixfetch = "nixfetch:run"

[project.urls]
source = "https://github.com/pfmephisto/nixfetch"
